rclone copy dropbox:Projects/ProjectilePointDatabase/ColoradoProjectilePointdatabase/training_dataset training_dataset
rclone copy dropbox:Projects/ProjectilePointDatabase/ColoradoProjectilePointdatabase/training_dataset_tmp training_dataset_tmp
rclone copy dropbox:Projects/ProjectilePointDatabase/ColoradoProjectilePointdatabase/training_masks training_masks
rclone copy dropbox:Projects/ProjectilePointDatabase/ColoradoProjectilePointdatabase/training_masks_tmp training_masks_tmp
